language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install codecov
before_script:
  - pip install pytest-cov
script:
  - py.test --cov=wechatkit tests/

after_success:
  - codecov
